---
- name: Create directory, log file, run command, and redirect output to logfile
  hosts: all
  tasks:
    - name: Run command
      shell: uptime
      register: uptime_output

    - name: write output
      copy:
         content: "{{ uptime_output }}"
         dest: "/tmp/uptime.txt"